# Generated by Django 3.0.6 on 2020-06-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.IntegerField()),
                ('Username', models.CharField(max_length=100)),
                ('Middlename', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Mothers_Name', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=50)),
                ('Religion', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Caste', models.CharField(max_length=100)),
                ('Mother_Tongue', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('pob', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Aadhar_no', models.BigIntegerField()),
                ('Bg', models.CharField(max_length=100)),
                ('Addr_of_com', models.CharField(max_length=100)),
                ('School_attended_by_the_child', models.CharField(max_length=100)),
                ('school_mob', models.BigIntegerField()),
                ('Gurdian_Name', models.CharField(max_length=100)),
                ('Relationship', models.CharField(max_length=100)),
                ('Contact_No', models.BigIntegerField()),
                ('fatherdob', models.DateField()),
                ('father_Quli', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('Mother_dob', models.DateField()),
                ('mother_Quli', models.CharField(max_length=100)),
                ('E_mail', models.EmailField(max_length=254)),
                ('father_mob', models.BigIntegerField()),
                ('parents_addr', models.CharField(max_length=100)),
                ('LGSPOKEH', models.CharField(max_length=100)),
                ('bestlang', models.CharField(max_length=100)),
                ('howtakecare', models.CharField(max_length=100)),
                ('speccial_needs', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('parentsign', models.ImageField(default='shri.jpg', upload_to='media')),
                ('aadhar', models.ImageField(default='shri.jpg', upload_to='media')),
                ('birthcirti', models.ImageField(default='shri.jpg', upload_to='media')),
                ('tc', models.ImageField(default='shri.jpg', upload_to='media')),
                ('Marksheet', models.ImageField(default='shri.jpg', upload_to='media')),
                ('san', models.ImageField(default='shri.jpg', upload_to='media')),
                ('IDProof', models.ImageField(default='shri.jpg', upload_to='media')),
            ],
        ),
    ]
