# Generated by Django 3.0.6 on 2020-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='stdphoto',
            field=models.ImageField(default='shri.jpg', upload_to='media'),
        ),
    ]
