# Generated by Django 3.0.6 on 2020-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_student_details_stdphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='place',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
