# Generated by Django 3.0.6 on 2020-06-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phno',
            field=models.BigIntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
