# Generated by Django 3.0.6 on 2020-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_admin_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.BigIntegerField()),
                ('Comment', models.CharField(max_length=400)),
            ],
        ),
    ]
