# Generated by Django 3.0.6 on 2020-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0006_inquary'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suser', models.CharField(max_length=100)),
                ('spin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='phno',
            field=models.BigIntegerField(),
        ),
    ]
