# Generated by Django 3.0.6 on 2020-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0007_auto_20200703_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuser', models.CharField(max_length=100)),
                ('tpin', models.CharField(max_length=100)),
            ],
        ),
    ]
