# Generated by Django 3.0.6 on 2020-07-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0008_teacher_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.IntegerField()),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
