# Generated by Django 3.0.6 on 2020-07-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0010_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
            ],
        ),
    ]
