# Generated by Django 3.0.6 on 2020-07-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0011_examq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='student_log',
            name='cls',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_log',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_log',
            name='rollno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
