# Generated by Django 3.0.6 on 2020-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0012_auto_20200719_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='meating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=100)),
                ('subj', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
